name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.10.14
  - pip=22.3.1
  - pytorch=1.12.0
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization-w-pose
    - submodules/simple-knn
